Repository fiamma-chain/networks, pull requests merged in 2024-11, with the labels that each got.

#42 Add validator BonyNode.json
  fiamma-testnet-1/bitvm2-staker-validators/BonyNode.json
Labels: balance-ok

#78 Create active-nodes.json
  fiamma-testnet-1/bitvm2-staker-validators/active-nodes.json
Labels: balance-ok

#76 Create KruGGoK-Stakesnodes.json
  fiamma-testnet-1/bitvm2-staker-validators/KruGGoK-Stakesnodes.json
Labels: balance-ok

#75 Add validator RPCdotcom.json
  fiamma-testnet-1/bitvm2-staker-validators/RPCdotcom.json
Labels: balance-ok

#73 Add validator kaplan.json
  fiamma-testnet-1/bitvm2-staker-validators/kaplan.json
Labels: balance-ok

#72 ♻️ PureNodes 💻 Validator Submission.json
  fiamma-testnet-1/bitvm2-staker-validators/♻️ PureNodes 💻.json
Labels: balance-ok

#71 Add files via upload
  fiamma-testnet-1/bitvm2-staker-validators/LuckyStar.json
Labels: balance-ok

#70 Create WellNode.json
  fiamma-testnet-1/bitvm2-staker-validators/validators/WellNode.json
Labels: balance-ok

#61 Add Validator SyaNodes.json
  fiamma-testnet-1/bitvm2-staker-validators/SyaNodes.json
Labels: balance-ok

#58 MictoNode Validator Submission
  fiamma-testnet-1/bitvm2-staker-validators/MictoNode.json
Labels: balance-ok

#56 Create Sychonix.json
  fiamma-testnet-1/bitvm2-staker-validators/Sychonix.json
Labels: balance-ok

#55 Add Perfect-nodes.json
  fiamma-testnet-1/bitvm2-staker-validators/Perfect-nodes.json
Labels: balance-ok

#52 Create Vinjan.Inc.json
  fiamma-testnet-1/bitvm2-staker-validators/Vinjan.Inc.json
Labels: balance-insufficient, balance-ok

#51 Create CroutonDigital.json
  fiamma-testnet-1/bitvm2-staker-validators/validators/CroutonDigital.json
Labels: balance-ok

#48 Create Endorphine-Stake.json
  fiamma-testnet-1/bitvm2-staker-validators/Endorphine-Stake.json
Labels: balance-ok, invalid-address

#49 Create MurphyNode.json
  fiamma-testnet-1/bitvm2-staker-validators/MurphyNode.json
Labels: balance-ok, invalid-address

#47 Create NODERS.json
  fiamma-testnet-1/bitvm2-staker-validators/validators/NODERS.json
Labels: balance-ok

#35 Add validator NodeStake.json
  fiamma-testnet-1/bitvm2-staker-validators/NodeStake.json
Labels: balance-insufficient, balance-ok

#16 Add validator Chicharito.json
  fiamma-testnet-1/bitvm2-staker-validators/Chicharito.json
Labels: balance-insufficient, balance-ok

#15 Add validator breskulpeak.com.json
  fiamma-testnet-1/bitvm2-staker-validators/breskulpeak.com.json
Labels: balance-ok

#14 Create oneplus.json
  fiamma-testnet-1/bitvm2-staker-validators/oneplus.json
Labels: balance-ok

#13 ADD validator Blackhox.json
  fiamma-testnet-1/bitvm2-staker-validators/Blackhox.json
Labels: balance-ok

#11 Create jayjay.json
  fiamma-testnet-1/bitvm2-staker-validators/jayjay.json
Labels: balance-ok

#10 Add validator ITRocket.json
  fiamma-testnet-1/bitvm2-staker-validators/ITRocket.json
Labels: balance-ok

#9 Create validator-79anvi.json
  fiamma-testnet-1/bitvm2-staker-validators/validator-79anvi.json
Labels: balance-ok

#8 Add validator StakeUp.json
  fiamma-testnet-1/bitvm2-staker-validators/StakeUp.json
Labels: balance-ok

#7 Add validator StingRay.json
  fiamma-testnet-1/bitvm2-staker-validators/StingRay.json
Labels: balance-ok

#39 Create CryptoSJnet.json
  fiamma-testnet-1/bitvm2-staker-validators/CryptoSJnet.json
Labels: balance-ok

#38 Create POSTHUMAN.json
  fiamma-testnet-1/bitvm2-staker-validators/POSTHUMAN.json
Labels: balance-ok

#34 Add validator STAVR.json
  fiamma-testnet-1/bitvm2-staker-validators/STAVR.json
Labels: balance-ok

#44 add validator ValidatorVN.json
  fiamma-testnet-1/bitvm2-staker-validators/ValidatorVN.json
Labels: balance-ok, invalid-address

#17 Add Validator NodeSafe.json
  fiamma-testnet-1/bitvm2-staker-validators/nodesafe.json
Labels: balance-insufficient, balance-ok

#23 Add validator MekongLabs.json
  fiamma-testnet-1/bitvm2-staker-validators/MekongLabs.json
Labels: balance-insufficient, balance-ok

#24 Add validator Straive.json
  .github/PULL_REQUEST_TEMPLATE/Straive.md
  fiamma-testnet-1/bitvm2-staker-validators/Straive.json
Labels: balance-insufficient, balance-ok

#25 add validator galaxynode.json
  fiamma-testnet-1/bitvm2-staker-validators/galaxynode.json
Labels: balance-insufficient, balance-ok

#37 Create CoinHunters.json
  fiamma-testnet-1/bitvm2-staker-validators/CoinHunters.json
Labels: balance-insufficient, balance-ok

#32 Add Validator Monkey Labs.json
  fiamma-testnet-1/bitvm2-staker-validators/Monkey Labs.json
Labels: balance-ok, invalid-address

#28 add validator zuka.json
  fiamma-testnet-1/bitvm2-staker-validators/zuka.json
Labels: balance-ok, invalid-address

#5 Request Pull Validator LAOCHO.json
  fiamma-testnet-1/bitvm2-staker-validators/LAOCHO.json
  fiamma-testnet-1/bitvm2-staker-validators/vaildator-template.json
Labels: balance-ok, invalid-address
